#[derive(Clone, Debug)]
pub enum TargetTriple {
    Host,
    String(String),
}

#[derive(Clone, Debug)]
pub enum TargetCpu {
    Host,
    String(String),
}

#[derive(Clone, Debug)]
pub enum Abi {
    Bare,
    Spectest,
}

// A Config specifies the global config for a build.
#[derive(Clone, Debug)]
pub struct Config {
    // ABI file(s)
    pub abi: Abi,
    pub abi_posix_wasi: &'static str,
    pub abi_spectest: &'static str,
    // Path of cc, usually the result of "$ which gcc".
    pub cc_binary: String,
    // Target. Example: target_triple="x86_64-pc-linux-gnu", target_cpu="broadwell"
    pub target_triple: TargetTriple,
    pub target_cpu: TargetCpu,
    // Path of wavm binary, usually the result of "$ which wavm".
    pub wavm_binary: String,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            abi: Abi::Bare,
            abi_posix_wasi: include_str!("../abi/posix_wasi_abi.h"),
            abi_spectest: include_str!("../abi/spectest.h"),
            target_triple: TargetTriple::Host,
            target_cpu: TargetCpu::Host,
            cc_binary: String::from("gcc"),
            wavm_binary: String::from("wavm"),
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct Middle {
    // Dir of abi.
    pub abi_path: std::path::PathBuf,
    // File of the abi.
    pub abi_file: std::path::PathBuf,
    // The middle AOT object file generated by aot_generator
    pub aot_object: std::path::PathBuf,
    // The middle AOT glue file generated by aot_generator
    pub aot_glue: std::path::PathBuf,
    // Config is the global config for a build.
    pub config: Config,
    // Dir is the caller's working directory, or the empty string to use
    // the current directory of the running process.
    pub dir: std::path::PathBuf,
    // Path of dummy file.
    pub dummy: std::path::PathBuf,
    // Source wasm/wast file.
    pub file: std::path::PathBuf,
    // File stem is the source wasm/wast file's name without extension.
    // Example:
    //   file_stem(helloworld.wasm) => helloworld
    pub file_stem: String,
    // Project address, usually equals to file.dirname
    pub prog_dir: std::path::PathBuf,
    // A directory on the file system that is deleted when build process stoped,
    // all temporary files during the build process will be stored here
    // Note: If you quit unexpectedly, it will not be cleaned up.
    // temp_dir: std::path::PathBuf,
    // Precompiled wasm file built by wavm.
    pub wavm_precompiled_wasm: std::path::PathBuf,
}

impl Middle {
    pub fn init_file<P: AsRef<std::path::Path>>(&mut self, p: P) {
        self.file = p.as_ref().to_path_buf();
        self.file_stem = self.file.file_stem().unwrap().to_str().unwrap().to_string();
        self.prog_dir = self.file.parent().unwrap().to_path_buf();
        if self.prog_dir.parent() == None {
            self.prog_dir = std::path::PathBuf::from("./");
        }
    }
}
